<div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="Login" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title">Nuevo giro</h4>
            </div>
            <div class="modal-body">
                <!-- The form is placed inside the body of modal -->
                <form id="loginForm" method="post" class="form-horizontal" role="form">
                    <div class="form-group">
                        <?php //echo $this->add->getElement('cod_modalidad_credito'); ?>
                        <div class="formulariogiro">
                            <label>Número de resolución:</label>

                            <?php echo $this->add->getElement('id_resolucion'); ?>
                        </div>
                        <div class="formulariogiro">
                            <label>Fecha:</label>
                            <?php echo $this->add->getElement('fecha_giro'); ?>
                        </div>
                        <div class="formulariogiro">
                            <label>Valor total:</label>
                            <?php echo $this->add->getElement('valor_total'); ?>
                        </div>
                    </div>
                    <div class="form-group">
                        <div align="right">
                            <?php echo $this->add->getElement('insertar'); ?>
                            <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                        </div>
                    </div>
                </form>
            </div>

        </div>
    </div>
</div>
<script type="text/javascript">
$('#sandbox-container').datepicker({
});
</script>