<?php

/*function fechaMysql($fecha)
    {
        $arr = split("-", $fecha);
        if (count($arr) != 3)
        {
            return $fecha;
        } else
        {
            return "$arr[2]-$arr[1]-$arr[0]";
        }
    }*/

?>
<aside>
    <div class="panel-primary panel">
        <div class="panel-heading"><h4 class="panel-title">GIROS</h4></div>
    </div>
    <div class="panel panel-body">
        <form class="form-inline form-group">                    
            <label>Filtrar por: </label>
            <div class="btn-group">
                <span class="label label-primary" style="padding: 5px;">Giro</span>
            </div>
            <div class="form-group">
                <select name="giro" class="form-control">
                    <option value="">Seleccione...</option>
                </select>
            </div>
            <div style="text-align: right" class="form-group">
                <input type="button" value="Buscar" class="btn btn-danger"/>
            </div>
        </form>
    </div>
    <div style="box-shadow: 1px 0px 5px 1px #cccccc;" class="panel panel-body">
        <table class="table table-striped table-bordered table-hover">
            <thead>
                <tr>
                    <th class="text-center">Resolución</th>
                    <th class="text-center">Fecha</th>
                    <th class="text-center">Valor giro total</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->mostrar as $m) : ?>
                    <tr>
                        <?php //$idmod = $mod->cod_modalidad_credito; ?>
                        <td ><?php echo $this->escape($m->id_resolucion); ?></td>
                        <td><?php echo $this->escape($m->fecha_giro); ?></td>
                        <!--<td><?php //echo $this->escape(fechaMysql($m->fecha_giro)); ?></td>-->
                        <td><?php echo $this->escape($m->valor_total); ?></td>
                        <td>
                            <div class="btn-group">
                                <button type="button" class="btn btn-default dropdown-toggle"data-toggle="dropdown">
                                    Opciones <span class="caret"></span>
                                </button>
                                <ul class="dropdown-menu" role="menu">
                                    <li><a data-toggle="modal" name='<?php echo $idmod; ?>' href="#verModal">Ver</a></li>
                                    <li class="divider"></li>
                                    <li><a href="<?php echo $this->url(array('module' => 'Modalidad', 'controller' => 'Modalidad', 'action' => 'actualizarmodalidad', 'id' => $idmod)); ?>">Editar</a></li>
                                    <li class="divider"></li>
                                    <li>
                                        <a data-href="<?php echo $this->url(array('module' => 'Modalidad', 'controller' => 'Modalidad', 'action' => 'eliminarmodalidad', 'id' => $idmod)); ?>" data-toggle="modal" data-target="#confirm-delete" href="#">
                                            Eliminar
                                        </a>
                                    </li>
                                </ul>

                            </div>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
           
        </table>
        <p class="text-right" style="margin-top: 20px;">
            <button class="btn btn-danger" data-toggle="modal" data-target="#loginModal">Ingresar nuevo giro</button>
            <!--<a href="<?php //echo $this->url(array('module' => 'Giros', 'controller' => 'Giro', 'action' => 'creargiro2')); ?>">Añadir recargando</a>-->
        </p>
         <!--Modal que contiene el formulario de añadir-->
        <?php echo $this->action('creargiro', 'Giro', 'Giros'); ?>
        <!---------------------------------------------->
    </div>
</aside>