<div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="Login" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title">Crear nuevo usuario</h4>
            </div>
            <div class="modal-body">
                <!-- The form is placed inside the body of modal -->
                <form id="usuario_form" method="post" class="form-horizontal" >
                    <div class="form-group">
                        <label class="col-xs-4 control-label">Nombre de usuario</label>
                        <div class="col-xs-7">
                            <?php echo $this->agrega->getElement('nombre_usuario'); ?>
                            <div id="nombre_usuario_aviso"></div>
                        </div>
                        <div id ='disponibilidad'></div>
                    </div>
                    <div class="form-group">
                        <label class="col-xs-4 control-label">Contraseña</label>
                        <div class="col-xs-7">
                            <?php echo $this->agrega->getElement('contrasena'); ?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-xs-4 control-label">Identificación</label>
                        <div class="col-xs-7">
                            <?php echo $this->agrega->getElement('identificacion'); ?>
                            <div id="identificacion_aviso"></div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-xs-4 control-label">Nombres</label>
                        <div class="col-xs-7">
                            <?php echo $this->agrega->getElement('nombre_real'); ?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-xs-4 control-label">Apellidos</label>
                        <div class="col-xs-7">
                            <?php echo $this->agrega->getElement('apellido_real'); ?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-xs-4 control-label">Cargo</label>
                        <div class="col-xs-7">
                            <?php echo $this->agrega->getElement('cargo'); ?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-xs-4 control-label">Perfil</label>
                        <div class="col-xs-7">
                            <?php echo $this->agrega->getElement('perfil'); ?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-xs-4 control-label">Estado</label>
                        <div class="col-xs-7">
                            <?php echo $this->agrega->getElement('estado'); ?>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-xs-7 col-xs-offset-3">
                            <?php echo $this->agrega->getElement('submit'); ?>
                            <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                        </div>
                    </div>
                </form>
                <div id ='popup' style ='display:none'><span class='button b-close'><span>X</span></span></div>
            </div>

        </div>
    </div>
</div>
<script>
     $('#usuario_form').submit(function(event){        
        var msj="";
        $('.required').each(function () {
            if(!$(this).val())
                {
                  msj += " El campo "+$(this).attr('name')+' es requerido<br>'; 
                }            
        });
        if(!!msj)
        {
         event.preventDefault();
          $('#popup').html('<span class="button b-close"><span>X</span></span>'+msj);
          $('#popup').bPopup({ easing: 'easeOutBack', speed: 450, transition: 'slideDown'});
          msj="";
        }                    
     });
</script>
<script>
    var tabla = (($('form').attr('id')).split("_"))[0]; 
    $('input').keyup(function(e){
            if($(this).hasClass('unico'))
            {
                var nombre_usuario = $(this).val();
                var columna = $(this).attr('id');
                $.post('usuario/disponible', {'nombre_usuario':nombre_usuario, 'tabla':tabla, 'columna':columna}, function(data) {
                $('#'+columna+'_aviso').html(data);
                });
            }
    });
</script>