<div id="verModal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title"><strong>Información de usuario</strong></h4>
            </div>
            <div class="modal-body">
                <div class="well" style="font-size: 16px;">
                    <span><strong>Nombre:</strong></span>
                    <span id="nombremodal" align="left"></span>
                    <div style="margin: 20px;">
                    <span><strong>Usuario:</strong></span>
                    <span id="usua" align="left"></span>
                    <span style="margin-left: 10px;"><strong>Perfil:</strong></span>
                    <span id="perfilmodal" align="left"></span>
                    <span style="margin-left: 10px;"><strong>Estado:</strong></span>
                    <span id="estadomodal" align="left"></span>
                    </div>
                    <div style="margin: 20px;">
                    
                    
                    <span><strong>Cargo:</strong></span>
                    <span id="cargomodal" align="left"></span>
                    <span style="margin-left: 10px;"><strong>Identificación:</strong></span>
                    <span id="idmodal" align="left"></span>
                    </div>
                    
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal">Cerrar</button>
                <!--<button type="button" class="btn btn-primary">Save changes</button>-->
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="confirm-delete" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">

            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">Confirma Eliminar</h4>
            </div>

            <div class="modal-body">
                <p>Esta a punto de eliminar el registro, este procedimiento es irreversible.</p>
                <p>¿Desea confirmar la operación?</p>
                <!--<p class="debug-url"></p>-->
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                <a href="#" class="btn btn-danger danger">Eliminar</a>
            </div>
        </div>
    </div>
</div>

<aside>
    <div class="panel-primary panel">
        <div class="panel-heading"><h4 class="panel-title">USUARIOS</h4></div>
    </div>
        
    <div style="box-shadow: 1px 0px 5px 1px #cccccc;" class="panel panel-body">
        <table id="usuario" class="table table-striped table-bordered table-hover">
            <thead>
                <tr>
                    <th class="text-center">Usuario</th>
                    <th class="text-center">Nombre</th>
                    <th class="text-center">Cargo</th>
                    <th class="text-center">Perfil</th>
                    <th class="text-center">Estado</th>
                    <th class="text-center">Identificación</th>
                    <th>&nbsp;</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->datos as $d) : ?>
                <tr>
                    <td id="tdd<?php echo $d->nombre_usuario; ?>" value="<?php echo $d->nombre_usuario; ?>"><?php echo $d->nombre_usuario; ?></td>
                    <td id="tdnom<?php echo $d->nombre_usuario; ?>" value="<?php echo $d->nombre_real . " " . $d->apellido_real; ?>"><?php echo $d->nombre_real . " " . $d->apellido_real; ?></td>
                    <td id="tdcargo<?php echo $d->nombre_usuario; ?>" value="<?php echo $this->escape($d->cargo); ?>"><?php echo $this->escape($d->cargo); ?></td>
                    <td id="tdperfil<?php echo $d->nombre_usuario; ?>" value="<?php echo $this->escape($d->perfil); ?>"><?php echo $this->escape($d->perfil); ?></td>
                    <td id="tdestado<?php echo $d->nombre_usuario; ?>" value="<?php echo $this->escape($d->estado); ?>"><?php echo $this->escape($d->estado); ?></td>
                    <td id="tdid<?php echo $d->nombre_usuario; ?>" value="<?php echo $this->escape($d->identificacion); ?>"><?php echo $this->escape($d->identificacion); ?></td>
                    <td>
                        <div class="btn-group">
                            <button type="button" class="btn btn-default dropdown-toggle"data-toggle="dropdown">
                              Opciones <span class="caret"></span>
                            </button>

                            <ul class="dropdown-menu" role="menu">
                              <li><a data-toggle="modal" name='<?php echo $d->nombre_usuario; ?>' href="#verModal">Ver</a></li>
                              <li class="divider"></li>
                              <li>
                                  <a href="<?php echo $this->url(array('module' => 'Usuarios', 'controller' => 'Usuario', 'action' => 'actualizarusuario', 'id' => $d->nombre_usuario)); ?>">
                                      Editar
                                  </a>
                              </li>
                              <li class="divider"></li>
                              <li><a data-href="<?php echo $this->url(array('module' => 'Usuarios', 'controller' => 'Usuario', 'action' => 'eliminarusuario', 'id' => $d->nombre_usuario)); ?>" data-toggle="modal" data-target="#confirm-delete" href="#">Eliminar</a></li>
                            </ul>
                          </div>
                    </td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
        <div align="right" style="margin-top: 20px;">
        <a class="btn btn-danger" data-toggle="modal" data-target="#loginModal">Ingresar nuevo usuario</a>
        </div>
        <!--Modal que contiene el formulario de añadir-->
        <?php echo $this->action('crearusuario', 'Usuario', 'Usuarios'); ?>
        <!---------------------------------------------->
        
   </div>
    
</aside>     

<script>
    $(document).ready(function(){
        var i=0;
        $('.dropdown-toggle').dropdown();
         $(function(){
            $(".sel").on('click', 'li a', function(){
                $("[id=sel] > h7").text($(this).text());
                $("[id=sel]").val($(this).text());
            });
        });
        $('#other').click(function(){
            $('#filter_1').clone().appendTo('#filter_1').attr('id','filter_'+i);
            i++;
        });
        
        $("#input:search").addClass("form-control");
        
        $('a').click(function() {
            $('span[id=usua]').text($('td[id=tdd' + $(this).attr('name') + ']').attr('value'));
            $('span[id=nombremodal]').text($('td[id=tdnom' + $(this).attr('name') + ']').attr('value'));
            $('span[id=cargomodal]').text($('td[id=tdcargo' + $(this).attr('name') + ']').attr('value'));
            $('span[id=perfilmodal]').text($('td[id=tdperfil' + $(this).attr('name') + ']').attr('value'));
            $('span[id=estadomodal]').text($('td[id=tdestado' + $(this).attr('name') + ']').attr('value'));
            $('span[id=idmodal]').text($('td[id=tdid' + $(this).attr('name') + ']').attr('value'));
            
        });
        $('#confirm-delete').on('show.bs.modal', function(e){
            $(this).find('.danger').attr('href', $(e.relatedTarget).data('href'));
        });
    });
</script>
   
