<aside>
    <div class="panel-primary panel">
        <div class="panel-heading"><h4 class="panel-title">CREDITOS</h4></div>
    </div>
    <div style="box-shadow: 1px 0px 5px 1px #cccccc;" class="panel panel-body">
        <table class="table table-striped table-bordered table-hover">
            <thead>
                <tr>
                    <th class="text-center">Periodo Academico</th>
                    <th class="text-center">Codigo</th>
                    <th class="text-center">Estado</th>
                    <th class="text-center">Modalidad</th>
                    <th class="text-center">Tipo Modalidad</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->creditos as $credito) : ?>
                    <tr>
                        <?php $idcredito = $credito->id; ?>
                        <td><?php echo $this->escape($credito['periodo_academico']); ?></td>
                        <td><?php echo $this->escape($credito['codigo_ud']); ?></td>
                        <td><?php echo $this->escape($credito['nombre_estado_credito']); ?></td>
                        <td><?php echo $this->escape($credito['nombre_modalidad']); ?></td>
                        <td><?php echo $this->escape($credito['nombre_tipo_modalidad']); ?></td>
                        <td>
                            <div class="btn-group">
                                <button type="button" class="btn btn-default dropdown-toggle"data-toggle="dropdown">
                                    Opciones <span class="caret"></span>
                                </button>
                                <ul class="dropdown-menu" role="menu">
                                    <li><a href="<?php echo $this->url(array('module' => 'Giros', 'controller' => 'Giro', 'action' => 'vergiro', 'id' => $idcredito)); ?>">Ver</a></li>
                                    <li class="divider"></li>
                                    <li><a href="<?php echo $this->url(array('module' => 'Giros', 'controller' => 'Giro', 'action' => 'editargiro', 'id' => $idcredito)); ?>">Editar</a></li>
                                    <li class="divider"></li>
                                    <li>
                                        <a data-href="<?php echo $this->url(array('module' => 'Modalidad', 'controller' => 'Modalidad', 'action' => 'eliminarmodalidad', 'id' => $idcredito)); ?>" data-toggle="modal" data-target="#confirm-delete" href="#">
                                            Eliminar
                                        </a>
                                    </li>
                                </ul>

                            </div>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
           
        </table>
        <p class="text-right" style="margin-top: 20px;">
            <button class="btn btn-danger" data-toggle="modal" data-target="#loginModal">Ingresar nuevo credito</button>
            <!--<a href="<?php //echo $this->url(array('module' => 'Giros', 'controller' => 'Giro', 'action' => 'creargiro2')); ?>">Añadir recargando</a>-->
        </p>
         <!--Modal que contiene el formulario de añadir-->
        <?php echo $this->action('creargiro', 'Giro', 'Giros'); ?>
        <!---------------------------------------------->
    </div>
</aside>