<aside>
    <div class="panel-primary panel">
        <div class="panel-heading"><h4 class="panel-title">ACTUALIZAR MODALIDAD DE CRÉDITO</h4></div>
    </div>
    <form class="panel panel-body" style="box-shadow: 1px 0px 5px 1px #cccccc;" method="post" id="formUpda">
        <table >
            <tr>
                <?php echo $this->form->getElement('cod_modalidad_credito'); ?>
                <td>Nombre de modalidad</td>
                <td><?php echo $this->form->getElement('nombre_modalidad_credito'); ?></td>
                <td>Descripción modalidad</td>
                <td><?php echo $this->form->getElement('descripcion_modalidad'); ?></td>
            </tr>
            <tr><td>&nbsp;</td></tr>
            <tr>
                <td colspan="4" align="right"><?php echo $this->form->getElement('submitmodalidad'); ?></td>
                <td><button class="btn btn-default" onclick="location.href='<?php echo $this->url(array('module'=>'Modalidad','controller'=>'Modalidad','action'=>'index')); ?>'">Cancelar</button></td>
            </tr>
        </table>
        <div id ='popup' style ='display:none'><span class='button b-close'><span>X</span></span></div>
    </form>
<?php //echo $this->form; ?>
</aside>
<script>
     $('#formUpda').submit(function(event){        
        var msj="";
        $('.required').each(function () {
            if(!$(this).val())
                {
                  msj += "<div style='padding:10px 40px 10px 40px;'><span style='color:#ff0000;'>&#x2605;</span>El campo "+$(this).attr('name')+' es requerido</div>'; 
                }            
        });
        if(!!msj)
        {
         event.preventDefault();
          $('#popup').html('<span class="button b-close"><span>X</span></span>'+msj);
          $('#popup').bPopup({ easing: 'easeOutBack', speed: 450, transition: 'slideDown'});
          msj="";
        }                    
     });
</script>