<?php echo $this->doctype() ?>
<html>
    <head>
        <?php 
        $session = new Zend_Session_Namespace('SuperAdmin');
        $auth = Zend_Auth::getInstance()->getIdentity();
        $perfil=$auth->perfil;
        $es=$auth->estado;
	//$perfil = $authStorage->perfil;
	/*if (!isset($perfil))
	{
	  $session = new Zend_Session_Namespace('Admin1');
	  $perfil = $session->getNamespace();
	}*/
        ?>
	<?php 
        $baseUrl = Zend_Controller_Front::getInstance()->getBaseUrl();
        echo $this->headMeta()->appendHttpEquiv('Content-Type', 'text/html; charset='.$this->getEncoding())->appendHttpEquiv('Content-Language', 'es-ES');
	echo $this->headTitle('.:.ICETEX.:.');
        
        $this->headLink()->appendStylesheet($baseUrl.'/bootstrap-3/dist/css/bootstrap.css');
        $this->headLink()->appendStylesheet($baseUrl.'/bootstrap-3/dist/css/bootstrap-datepicker.css');
	$this->headLink()->appendStylesheet($baseUrl.'/css/css.css');
	$this->headLink()->appendStylesheet($baseUrl.'/bootstrap-3/examples/signin/signin.css');
        $this->headLink()->appendStylesheet($baseUrl.'/bpopup/css/style.min.css');
        $this->headLink()->appendStylesheet($baseUrl.'/datatables/media/css/jquery.dataTables.css');
        //$this->headLink()->appendStylesheet($baseUrl.'/validatrix/css/validatrix.css');
        //$this->headLink()->appendStylesheet($baseUrl.'/bootstrap-3/js/modal.js');
        echo $this->headLink();
        
	$this->headScript()->appendFile($baseUrl.'/bootstrap-3/assets/js/jquery.js');
        //$this->headScript()->appendFile($baseUrl.'/bootstrap-3/jquery-1.8.3.min.js');
	$this->headScript()->appendFile($baseUrl.'/bootstrap-3/dist/js/bootstrap.js');
        $this->headScript()->appendFile($baseUrl.'/bootstrap-3/dist/js/bootstrap-datepicker.js');
        //$this->headLink()->appendStylesheet($baseUrl.'/bootstrap-3/dist/js/bootstrap.min.js');
	//$this->headScript()->appendFile('/js/common.js');
        $this->headScript()->appendFile($baseUrl.'/bpopup/js/jquery.bpopup.min.js');
        $this->headScript()->appendFile($baseUrl.'/custom/datatables.js');
        //$this->headScript()->appendFile($baseUrl.'/validatrix/js/validatrix.js');
        $this->headScript()->appendFile($baseUrl.'/datatables/media/js/jquery.dataTables.js');
        $this->headScript()->appendFile($baseUrl.'/easing/jquery.easing.1.3.js');
	echo $this->headScript();?>
	<link rel="shortcut icon" type="image/x-icon" href="<?php echo $baseUrl; ?>/imagenes/favicon.ico" />
    </head>
<body>
    <header>
	<img src="<?php echo $baseUrl;?>/imagenes/banner1.png" style="width: 100%;" />
    </header>
    
    <nav <?php if (isset($perfil)) { ?> class="navbar navbar-default" <?php } ?> role="navigation">
      <?php if (isset($perfil)) {
	  echo $this->render('nav.phtml');
      } ?>
    </nav>
    
    <article style="margin-left: 5%;">
      <?php if (isset($perfil)){ ?>
      <div role="navigation" class="list-group">
	<?php echo $this->render('menu.phtml'); ?>
      </div>
      <?php }?>
    </article>
    
    <?php echo $this->layout()->content; ?>  
    
    <footer><cite>Universidad Distrital Francisco José de Caldas</cite></footer>  
    
</body>    

</html>
