<?php
$auth = Zend_Auth::getInstance();
$authStorage = $auth->getIdentity();
?>
<!-- El logotipo y el icono que despliega el menú se agrupan
     para mostrarlos mejor en los dispositivos móviles -->
<div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Desplegar navegación</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="#">SISBIUD - ICETEX</a>
</div>

<!-- Agrupar los enlaces de navegación, los formularios y cualquier
     otro elemento que se pueda ocultar al minimizar la barra -->
<div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav">
        <li><a href="#" class="navbar-link">Bienvenido <?php echo $authStorage->nombre_real . " " . $authStorage->apellido_real; ?></a></li>
        <li><a>Perfil: <?php echo $authStorage->perfil; ?></a></li>
        
        <li><a>Estado: <?php echo $authStorage->estado; ?></a></li>
      
    </ul>

    <ul class="nav navbar-nav navbar-right">
        <a class="btn btn-primary btn-sm navbar-btn" href='<?php echo $this->url(array('module' => 'Index', 'controller' => 'Index', 'action' => 'logout')); ?>'>Cerrar Sesión</a>
    </ul>
</div>